### ISSUE TITLE
Missing field_seo column in content table

### ISSUE THREAD

**Issue by xavianaxw** [ethercreative/seo#124]
### Description

I installed the plugin locally and everything works smoothly. Upon deploying to my site via capistrano, the following error occurs.

My Full Stack Trace

```
TypeError: Argument 1 passed to craft\services\Plugins::getPluginHandleByClass() must be of the type string, null given, called in /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/base/MissingComponentTrait.php on line 117 and defined in /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/services/Plugins.php:303
Stack trace:
#0 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/base/MissingComponentTrait.php(117): craft\services\Plugins->getPluginHandleByClass(NULL)
#1 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/fields/MissingField.php(48): craft\fields\MissingField->getPlaceholderHtml()
#2 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Extension/Core.php(1619): craft\fields\MissingField->getInputHtml(NULL, Object(craft\elements\Entry))
#3 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\fields\MissingField), 'getInputHtml', Array, 'method', false, false)
#4 /var/www/staging.thewellresource.org.au/shared/craft/storage/runtime/compiled_templates/1f/1f3c6d36616cef862c2e767debe4ee83070adff6fafc1859461106c60da6096f.php(83): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\fields\MissingField), 'getInputHtml', Array, 'method')
#5 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_49d06bd377fe3f1edcb45f5c71dde880c01a3f665f479f905899b14de6caffea->doDisplay(Array, Array)
#6 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#7 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#8 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#9 /var/www/staging.thewellresource.org.au/shared/craft/storage/runtime/compiled_templates/ab/ab7955e07b8f1fa2e6e8b8b9e03f185e02322a43e57048c439c1c362aade7d13.php(47): craft\web\twig\Template->display(Array)
#10 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_26886d6dbd4a82a3478aa96d87d51e65dc33871a33c27f7ab4377fba9a96987d->doDisplay(Array, Array)
#11 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#12 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#13 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#14 /var/www/staging.thewellresource.org.au/shared/craft/storage/runtime/compiled_templates/fa/fa5d889c67caef0013865f09da81f3d29d5ca49af3362be9bcd1a630eb53b73c.php(59): craft\web\twig\Template->display(Array)
#15 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_283d4c08817245315aea8abd36b973b725db556715639f7dffeb3765ae9e131d->doDisplay(Array, Array)
#16 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#17 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#18 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#19 /var/www/staging.thewellresource.org.au/shared/craft/storage/runtime/compiled_templates/60/6033084655c71c5c1a7325e4c143b72d32411aa6a0c0297cdf188cf0ee926c73.php(434): craft\web\twig\Template->display(Array)
#20 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_05600adffd1398daa780f5ab6bc84f8afa752da6ccc2a48958a0657057a95865->block_content(Array, Array)
#21 /var/www/staging.thewellresource.org.au/shared/craft/storage/runtime/compiled_templates/39/39011d22d5e2b172a5c4c9da4827673c386e7b73cf30654b147c3110b3d2708d.php(639): Twig_Template->displayBlock('content', Array, Array)
#22 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_0bc7b09aab723189c781db91fafac00a74a0367845a2ba4d1e05f2fa17730749->block_main(Array, Array)
#23 /var/www/staging.thewellresource.org.au/shared/craft/storage/runtime/compiled_templates/39/39011d22d5e2b172a5c4c9da4827673c386e7b73cf30654b147c3110b3d2708d.php(536): Twig_Template->displayBlock('main', Array, Array)
#24 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_0bc7b09aab723189c781db91fafac00a74a0367845a2ba4d1e05f2fa17730749->block_body(Array, Array)
#25 /var/www/staging.thewellresource.org.au/shared/craft/storage/runtime/compiled_templates/b6/b6579f6e6501dd4c35f9f0a0a1407d323b43d393c5f517187bbc67ab21c0a132.php(60): Twig_Template->displayBlock('body', Array, Array)
#26 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_41420e53fd30f48f17120e0bc6a97259204d8f63dccab19339430d23adc1f5cf->doDisplay(Array, Array)
#27 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#28 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#29 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#30 /var/www/staging.thewellresource.org.au/shared/craft/storage/runtime/compiled_templates/14/146f78924eb40e2be47aa5a95fa9201d1e7d1d6263ee7cca36df54a84b6cdab1.php(40): craft\web\twig\Template->display(Array, Array)
#31 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_21ee1d2a73166d9fb265790fe43ccd311b4d16796df4f59f143c82e8f09dbdcb->doDisplay(Array, Array)
#32 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#33 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#34 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#35 /var/www/staging.thewellresource.org.au/shared/craft/storage/runtime/compiled_templates/39/39011d22d5e2b172a5c4c9da4827673c386e7b73cf30654b147c3110b3d2708d.php(94): craft\web\twig\Template->display(Array, Array)
#36 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_0bc7b09aab723189c781db91fafac00a74a0367845a2ba4d1e05f2fa17730749->doDisplay(Array, Array)
#37 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#38 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#39 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#40 /var/www/staging.thewellresource.org.au/shared/craft/storage/runtime/compiled_templates/60/6033084655c71c5c1a7325e4c143b72d32411aa6a0c0297cdf188cf0ee926c73.php(62): craft\web\twig\Template->display(Array, Array)
#41 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(390): __TwigTemplate_05600adffd1398daa780f5ab6bc84f8afa752da6ccc2a48958a0657057a95865->doDisplay(Array, Array)
#42 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#43 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(367): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#44 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#45 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Template.php(375): craft\web\twig\Template->display(Array)
#46 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#47 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/View.php(330): Twig_Environment->render('entries/_edit', Array)
#48 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/View.php(377): craft\web\View->renderTemplate('entries/_edit', Array)
#49 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/Controller.php(155): craft\web\View->renderPageTemplate('entries/_edit', Array)
#50 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/controllers/EntriesController.php(378): craft\web\Controller->renderTemplate('entries/_edit', Array)
#51 [internal function]: craft\controllers\EntriesController->actionEditEntry('test', NULL, NULL, NULL, NULL, Object(craft\elements\Entry))
#52 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#53 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#54 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('edit-entry', Array)
#55 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#56 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('entries/edit-en...', Array)
#57 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#58 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/craftcms/cms/src/web/Application.php(271): yii\web\Application->handleRequest(Object(craft\web\Request))
#59 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#60 /var/www/staging.thewellresource.org.au/releases/20180801072901/craft/web/index.php(21): yii\base\Application->run()
#61 {main}
```

I've also noticed that I am missing my `field_seo` column within my `content` table.

If it helps, someone did install the plugin via backend and removed it before i made the deployment.

### Steps to reproduce

I am unable to reproduce it.

### Additional info

- Craft version: 3.0.18
- SEO version: 3.3
- PHP version: 7.0.30 on ubuntu
- Database driver & version: MySQL Ver 14.14 Distrib 5.7.22, for Linux (x86_64)
- Other Plugins:

```
"vlucas/phpdotenv": "^2.4.0",
"studioespresso/craft-dumper": "1.3.1",
"verbb/super-table": "2.0.7",
"verbb/field-manager": "2.0.2",
"craftcms/redactor": "2.1.5",
"mmikkel/child-me": "1.0.4",
"craftcms/aws-s3": "^1.0",
```

**Comment by Tam** [comment]
@xavianaxw Am I right in thinkning that the plugin is no longer installed? It seems to me that you are trying to render an SEO field without the SEO plugin being installed. If you check in the fields section of Craft you'll probably see some red text next to one of the fields telling you that a class is missing.

**Comment by xavianaxw** [comment]
You were right @Tam the field did become a `MissingField` when someone removed it from the plugin list. Fat yikes from me.

![screen shot 2018-08-02 at 10 23 53 am](https://user-images.githubusercontent.com/8082158/43555554-32dada2c-963e-11e8-98a7-a5f4d2a6d982.png)

Thanks again!
