### ISSUE TITLE
Exception while saving entry

### ISSUE THREAD

**Issue by GuidoNeele** [ethercreative/seo#133]
### Description

When saving an entry the following exception is given:

```
TypeError: Argument 3 passed to ether\seo\models\data\SeoData::__construct() must be of the type array, object given, called in /.../craft/vendor/ether/seo/src/fields/SeoField.php on line 82 and defined in /.../craft/vendor/ether/seo/src/models/data/SeoData.php:71
Stack trace:
#0 /.../craft/vendor/ether/seo/src/fields/SeoField.php(82): ether\seo\models\data\SeoData->__construct(Object(ether\seo\fields\SeoField), Object(craft\elements\Entry), Object(ether\seo\models\data\SeoData))
#1 /.../craft/vendor/craftcms/cms/src/base/Element.php(1936): ether\seo\fields\SeoField->normalizeValue(Object(ether\seo\models\data\SeoData), Object(craft\elements\Entry))
#2 /.../craft/vendor/craftcms/cms/src/base/Element.php(793): craft\base\Element->normalizeFieldValue('seo')
#3 /.../craft/vendor/yiisoft/yii2/base/ArrayableTrait.php(126): craft\base\Element->__get('seo')
#4 /.../craft/vendor/craftcms/cms/src/web/View.php(504): yii\base\Model->toArray(Array, Array, false)
#5 /.../craft/vendor/craftcms/cms/src/helpers/ElementHelper.php(149): craft\web\View->renderObjectTemplate('jobs/{{ (_varia...', Object(craft\elements\Entry), Array)
#6 /.../craft/vendor/craftcms/cms/src/helpers/ElementHelper.php(92): craft\helpers\ElementHelper::_renderUriFormat('jobs/{slug}', Object(craft\elements\Entry))
#7 /.../craft/vendor/craftcms/cms/src/validators/ElementUriValidator.php(49): craft\helpers\ElementHelper::setUniqueUri(Object(craft\elements\Entry))
#8 /.../craft/vendor/yiisoft/yii2/validators/Validator.php(267): craft\validators\ElementUriValidator->validateAttribute(Object(craft\elements\Entry), 'uri')
#9 /.../craft/vendor/yiisoft/yii2/base/Model.php(367): yii\validators\Validator->validateAttributes(Object(craft\elements\Entry), Array)
#10 /.../craft/vendor/craftcms/cms/src/services/Elements.php(404): yii\base\Model->validate()
#11 /.../craft/vendor/craftcms/cms/src/services/Elements.php(1395): craft\services\Elements->saveElement(Object(craft\elements\Entry), true, false)
#12 /.../craft/vendor/craftcms/cms/src/services/Elements.php(500): craft\services\Elements->_propagateElement(Object(craft\elements\Entry), false, Array)
#13 /.../craft/vendor/craftcms/cms/src/controllers/EntriesController.php(544): craft\services\Elements->saveElement(Object(craft\elements\Entry))
#14 [internal function]: craft\controllers\EntriesController->actionSaveEntry()
#15 /.../craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#16 /.../craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#17 /.../craft/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save-entry', Array)
#18 /.../craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-entry', Array)
#19 /.../craft/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('entries/save-en...', Array)
#20 /.../craft/vendor/craftcms/cms/src/web/Application.php(538): craft\web\Application->runAction('entries/save-en...', Array)
#21 /.../craft/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#22 /.../craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#23 /.../httpdocs/index.php(21): yii\base\Application->run()
#24 {main}
```

### Additional info

- Craft version: 3.0.23.1
- SEO version: 3.4.1
- PHP version: 7.0.31
- Database driver & version: MySQL 5.5.5
- Other Plugins:

Advanced Url Field 1.0.0
Craft Emailobfuscator 2.0.0-beta.1
Freeform 2.2.2
MailChimp Lists 1.0.5
Mandrill 1.2.0
Position Fieldtype 1.0.13
Redactor 2.1.6
Super Table 2.0.8
Template Select 2.0.0

**Comment by Tam** [comment]
Fixed in [v3.4.2](https://github.com/ethercreative/seo/releases/tag/v3.4.2)

**Comment by GuidoNeele** [comment]
Holy cow, you guys are fast :-)
Thanks! Can confirm problem is fixed.

**Comment by janhenckens** [comment]
I'm running into this issue on the latest version of the plugin. Craft 3.0.29, SEO 3.4.4
Can you have anothe look?
