### ISSUE TITLE
3.1: Setting read-only property: ether\seo\models\data\SeoData::title

### ISSUE THREAD

**Issue by riasvdv** [ethercreative/seo#170]
### Description
When opening an entry on 3.1 I get the following error: Setting read-only property: ether\seo\models\data\SeoData::title

```
yii\base\InvalidCallException: Setting read-only property: ether\seo\models\data\SeoData::title in /Users/rias/Code/craft/vendor/yiisoft/yii2/base/BaseObject.php:161
Stack trace:
#0 /Users/rias/Code/craft/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\BaseObject->__set('title', NULL)
#1 /Users/rias/Code/craft/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(ether\seo\models\data\SeoData), Array)
#2 /Users/rias/Code/craft/vendor/ether/seo/src/models/data/SeoData.php(184): yii\base\BaseObject->__construct(Array)
#3 /Users/rias/Code/craft/vendor/ether/seo/src/fields/SeoField.php(101): ether\seo\models\data\SeoData->__construct(Object(ether\seo\fields\SeoField), Object(craft\elements\Entry), Array)
#4 /Users/rias/Code/craft/vendor/craftcms/cms/src/base/Element.php(2007): ether\seo\fields\SeoField->normalizeValue(Array, Object(craft\elements\Entry))
#5 /Users/rias/Code/craft/vendor/craftcms/cms/src/base/Element.php(1645): craft\base\Element->normalizeFieldValue('seo')
#6 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Extension/Core.php(1626): craft\base\Element->getFieldValue('seo')
#7 /Users/rias/Code/craft/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\elements\Entry), 'getFieldValue', Array, 'method', false, false)
#8 /Users/rias/Code/craft/storage/runtime/compiled_templates/2d/2d5a49cb11928026aa48c4f0d00759f336dac32dec05381b4fa4e3ae6abefe74.php(30): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\elements\Entry), 'getFieldValue', Array, 'method')
#9 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_1b9564e1c0d13600f111efec161f81e31c908a87dc133a5e6f27ec198db06589->doDisplay(Array, Array)
#10 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#11 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#12 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#13 /Users/rias/Code/craft/storage/runtime/compiled_templates/13/13c71dcad7084181737a5ab139f46601abd72a872b755831111a92bdd61253d7.php(47): craft\web\twig\Template->display(Array)
#14 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_f2c3393d3148241271b4dfab7234c5819efb125aa2ef3737a37fdfdce554344c->doDisplay(Array, Array)
#15 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#16 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#17 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#18 /Users/rias/Code/craft/storage/runtime/compiled_templates/28/28dab2195958fe3b3f154284aad3694930ac33efd73d42583f5b34476c9e6dab.php(59): craft\web\twig\Template->display(Array)
#19 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_8896fef79266b6972c2621390b9317d1faba7ebcd21c3b8c4e7f6e949e4908a9->doDisplay(Array, Array)
#20 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#21 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#22 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#23 /Users/rias/Code/craft/storage/runtime/compiled_templates/42/422b664efda2de5147063cd43a1dd7050c94b006bac36d212d724b5f0e119e21.php(434): craft\web\twig\Template->display(Array)
#24 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_fd40387c37a6f03445271b1ef06fc1f00370967454b7df4537d928d3be203c51->block_content(Array, Array)
#25 /Users/rias/Code/craft/storage/runtime/compiled_templates/8b/8b4573bdbd08ee0837548a7f909b5ef4e76d19a8a1710c6cb29b8ddec77d6b8a.php(648): Twig_Template->displayBlock('content', Array, Array)
#26 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_69c01bf0eae7afa733394320de7114dff5712fd75c8e0164f24d4dcd1728ec54->block_main(Array, Array)
#27 /Users/rias/Code/craft/storage/runtime/compiled_templates/8b/8b4573bdbd08ee0837548a7f909b5ef4e76d19a8a1710c6cb29b8ddec77d6b8a.php(533): Twig_Template->displayBlock('main', Array, Array)
#28 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_69c01bf0eae7afa733394320de7114dff5712fd75c8e0164f24d4dcd1728ec54->block_body(Array, Array)
#29 /Users/rias/Code/craft/storage/runtime/compiled_templates/b6/b6e7d1f295737d368209d86013ebfd823cbe0d7316f3159cc8f1d6a49101e3a0.php(60): Twig_Template->displayBlock('body', Array, Array)
#30 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_bc69428cffeba8ee7ac8fa1d7b60a6c72564b1e55eca50f3231a75cc3d113121->doDisplay(Array, Array)
#31 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#32 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#33 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#34 /Users/rias/Code/craft/storage/runtime/compiled_templates/cf/cf46c713a37ca6185f3d9689c43da5bc3c9025ce6637b14602a3aa5f51e62ea8.php(40): craft\web\twig\Template->display(Array, Array)
#35 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_2271234e58579e8af4c9bd1b46d7cc9fd6ef965390a83bab1ed0ec42e55349ed->doDisplay(Array, Array)
#36 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#37 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#38 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#39 /Users/rias/Code/craft/storage/runtime/compiled_templates/8b/8b4573bdbd08ee0837548a7f909b5ef4e76d19a8a1710c6cb29b8ddec77d6b8a.php(95): craft\web\twig\Template->display(Array, Array)
#40 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_69c01bf0eae7afa733394320de7114dff5712fd75c8e0164f24d4dcd1728ec54->doDisplay(Array, Array)
#41 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#42 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#43 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#44 /Users/rias/Code/craft/storage/runtime/compiled_templates/42/422b664efda2de5147063cd43a1dd7050c94b006bac36d212d724b5f0e119e21.php(62): craft\web\twig\Template->display(Array, Array)
#45 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_fd40387c37a6f03445271b1ef06fc1f00370967454b7df4537d928d3be203c51->doDisplay(Array, Array)
#46 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#47 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#48 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#49 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->display(Array)
#50 /Users/rias/Code/craft/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#51 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/View.php(337): Twig_Environment->render('entries/_edit', Array)
#52 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/View.php(384): craft\web\View->renderTemplate('entries/_edit', Array)
#53 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('entries/_edit', Array)
#54 /Users/rias/Code/craft/vendor/craftcms/cms/src/controllers/EntriesController.php(385): craft\web\Controller->renderTemplate('entries/_edit', Array)
#55 [internal function]: craft\controllers\EntriesController->actionEditEntry('pages', 2, NULL, NULL, NULL, Object(craft\elements\Entry))
#56 /Users/rias/Code/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#57 /Users/rias/Code/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#58 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('edit-entry', Array)
#59 /Users/rias/Code/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#60 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('entries/edit-en...', Array)
#61 /Users/rias/Code/craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#62 /Users/rias/Code/craft/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#63 /Users/rias/Code/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#64 /Users/rias/Code/craft/web/index.php(21): yii\base\Application->run()
#65 /Users/rias/.composer/vendor/laravel/valet/server.php(151): require('/Users/rias/Cod...')
#66 {main}
```

### Steps to reproduce

1. Open an entry when SEO is installed on 3.1

### Additional info

- Craft version: 3.1.2.2
- SEO version: latest
- PHP version: 7.2

**Comment by shgzon** [comment]
Hello @Rias500, I am still getting this error.. Any idea how to fix this?

**Comment by riasvdv** [comment]
It just disappeared for me, so I thought I did something wrong

**Comment by dowadidi** [comment]
Same issue here. Identical setup and similar error: `Setting read-only property: ether\seo\models\data\SeoData::description`
