### ISSUE TITLE
Migration error upgrading to 3.1

### ISSUE THREAD

**Issue by JayBox325** [ethercreative/seo#190]
### Description

I have run `./craft update all` to get all the latest plugin updates and I got an error at the migrations stage of the update. When I visit the CMS to run the changes the database requires after an update in the command line I get the following error message:

``` 
Database Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'siteId'
The SQL being executed was: ALTER TABLE craft_seo_redirects ADD siteId int(11) NULL DEFAULT NULL

Migration: ether\seo\migrations\m180906_152947_add_site_id_to_redirects

Output:

> add column siteId integer NULL DEFAULT NULL to table {{%seo_redirects}} ...Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'siteId'
The SQL being executed was: ALTER TABLE craft_seo_redirects ADD siteId int(11) NULL DEFAULT NULL (/Users/jaycollett/Development/stf/build/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /Users/jaycollett/Development/stf/build/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /Users/jaycollett/Development/stf/build/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE cr...')
#2 /Users/jaycollett/Development/stf/build/vendor/yiisoft/yii2/db/Migration.php(377): yii\db\Command->execute()
#3 /Users/jaycollett/Development/stf/build/vendor/ether/seo/src/migrations/m180906_152947_add_site_id_to_redirects.php(21): yii\db\Migration->addColumn('{{%seo_redirect...', 'siteId', Object(craft\db\mysql\ColumnSchemaBuilder))
#4 /Users/jaycollett/Development/stf/build/vendor/craftcms/cms/src/db/Migration.php(56): ether\seo\migrations\m180906_152947_add_site_id_to_redirects->safeUp()
#5 /Users/jaycollett/Development/stf/build/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#6 /Users/jaycollett/Development/stf/build/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(ether\seo\migrations\m180906_152947_add_site_id_to_redirects))
#7 /Users/jaycollett/Development/stf/build/vendor/craftcms/cms/src/services/Updates.php(223): craft\db\MigrationManager->up()
#8 /Users/jaycollett/Development/stf/build/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
#9 /Users/jaycollett/Development/stf/build/vendor/craftcms/cms/src/controllers/UpdaterController.php(209): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /Users/jaycollett/Development/stf/build/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/jaycollett/Development/stf/build/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /Users/jaycollett/Development/stf/build/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('migrate', Array)
#14 /Users/jaycollett/Development/stf/build/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#15 /Users/jaycollett/Development/stf/build/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('updater/migrate', Array)
#16 /Users/jaycollett/Development/stf/build/vendor/craftcms/cms/src/web/Application.php(683): craft\web\Application->runAction('updater/migrate')
#17 /Users/jaycollett/Development/stf/build/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /Users/jaycollett/Development/stf/build/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /Users/jaycollett/Development/stf/build/public/index.php(21): yii\base\Application->run()
#20 {main}
```

### Steps to reproduce

1.
2.

### Additional info

- Craft version: Upgrading to 3.1.8
- SEO version: Upgrading to 3.5.4
- PHP version:
- Database driver & version:
- Other Plugins:

**Comment by JayBox325** [comment]
I have just deleted the `siteId` row from my `craft_seo_redirects` table in SequelPro and it seems to have resolved itself, however, I'm going to leave this ticket open because I'd still be interested in your thoughts on this issue.

Thanks.

**Comment by Tam** [comment]
Closing this since you seemed to have fixed the issue.
