### ISSUE TITLE
3.6.2 Fatal Server Error

### ISSUE THREAD

**Issue by xaddict** [ethercreative/seo#239]
### Description
When using SEO 3.6.2 field in a content type on Craft CMS 3.2.9 I get a Fatal server error when I try to edit an Entry.

If i disable the plugin everything is alright again. The debug toolbar mentions

```
yii\base\ErrorException: preg_replace(): Unknown modifier 'z' in /home/deb116357/domains/zoslimbereikbaar.nl/public_html/vendor/craftcms/cms/src/web/twig/Extension.php:468
```

### Steps to reproduce

1. Create Section, Content type with SEO field in it
2. Try to create or edit an entry with that SEO field in it.

### Additional info

- Craft version: Craft Pro 3.2.9
- SEO version: 3.6.2
- PHP version: 7.3.7
- Database driver & version: MySQL 5.5.5
- Other Plugins:

Plugin | Version
----- | -----
Conditions | 1.0.3
Entry Instructions | 1.0.4
Inventory | 2.0.3
Mix | 1.5.2
Position Fieldtype | 1.0.14
Redactor | 2.3.3.2
Super Table | 2.2.1

**Comment by EternalBlack** [comment]
I got the very same problem on a production environment currently. This is kind of a major issue for us. :s

**Comment by jesuismaxime** [comment]
Got the same issue but with a `a` modifier
`preg_replace(): Unknown modifier 'a'`

Note: Got this issue on local env (on two separate computer), but not on dev env (thankfully this project is not on production environment, but we've several Craft3 site online on prod environment using this plugin).


PHP version | 7.3.7
-- | --
Darwin 18.2.0
MySQL 5.7.26
Imagick 3.4.3 (ImageMagick 6.9.6-2)
Craft Pro 3.2.10
2.0.21
2.11.3
6.3.3
1.2.3-dev


SEO | 3.6.2
-- | --

**Comment by satcreative** [comment]
Same issue but with 'C' modifier
`preg_replace(): Unknown modifier 'c'`

Seeing this in local and production. Began when I ran the most recent update for Craft cms and ethercreative/seo

![Screenshot 2019-09-04 at 16 33 42](https://user-images.githubusercontent.com/12640985/64269510-e5f69380-cf31-11e9-896c-7719d29e9e58.png)

SEO 3.6.2

**Comment by xaddict** [comment]
Yep. 3.6.2 seems to be evil.

**Comment by Tam** [comment]
I can't recreate this issue, can anyone supply me with a full stacktrace?

**Comment by jesuismaxime** [comment]
Do you know when the previously referenced commit will be released ?

Update to from `Craft Pro 3.2.10` to `3.3.17` didnt solve anything. Here's a trace just in case :

```
yii\base\ErrorException: preg_replace(): Unknown modifier 'c' in /the-site/vendor/craftcms/cms/src/web/twig/Extension.php:490
Stack trace:
#0 /the-site/vendor/craftcms/cms/src/web/ErrorHandler.php(80): yii\base\ErrorHandler->handleError(2, 'preg_replace():...', '/the-site/...', 490)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'preg_replace():...', '/the-site/...', 490, Array)
#2 /the-site/vendor/craftcms/cms/src/web/twig/Extension.php(490): preg_replace('//site.local/', '', 'http://site.loc...')
#3 /the-site/storage/runtime/compiled_templates/f4/f4fc0373b148425ae37586779745c9ac184a03babe9179d6ebcbf04ad5a044df.php(174): craft\web\twig\Extension->replaceFilter('http://site.loc...', '//site.local/', '')
#4 /the-site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_3ba990ebef246fc6e2b8548b9fdd7e68a781fd25a296d3e5c8881c982258a1f4->doDisplay(Array, Array)
#5 /the-site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /the-site/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#7 /the-site/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#8 /the-site/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#9 /the-site/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('seo/_seo/fieldt...', Array)
#10 /the-site/vendor/ether/seo/src/fields/SeoField.php(270): craft\web\View->renderTemplate('seo/_seo/fieldt...', Array)
#11 /the-site/vendor/twig/twig/src/Extension/CoreExtension.php(1485): ether\seo\fields\SeoField->getInputHtml(Object(ether\seo\models\data\SeoData), Object(craft\elements\Entry))
#12 /the-site/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(ether\seo\fields\SeoField), 'getInputHtml', Array, 'method', false, false)
#13 /the-site/storage/runtime/compiled_templates/3c/3ceb7f9ad313d8b232b3eae9511b195981d87f14d0a697f9b81c9bdb1ef8f14c.php(98): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(ether\seo\fields\SeoField), 'getInputHtml', Array, 'method')
#14 /the-site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_fa462544f6edc01d58bc2f565ae7296b14bb2ec4b5faf0a21235aed79bf8f33f->doDisplay(Array, Array)
#15 /the-site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /the-site/storage/runtime/compiled_templates/45/45d81d8476a8ad9461d4f0a832b2f2e0fa2c13b63d3816434776a329e53f7d4d.php(62): Twig\Template->display(Array)
#17 /the-site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_6563f708906713ec71af326d690949f5bc14ae78491a974110f9573192c811b4->doDisplay(Array, Array)
#18 /the-site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /the-site/storage/runtime/compiled_templates/a7/a7ba47a27912c9cabd50550bc8d68725b66918c506742a7769c3a1a17aedf09a.php(74): Twig\Template->display(Array)
#20 /the-site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_e2dce57dc2a198c3c7764e1a5f04c86762b79ecaaf5810cbf8bd67be3a9848ed->doDisplay(Array, Array)
#21 /the-site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /the-site/storage/runtime/compiled_templates/f5/f5786a68aadd3942d43017cad7ce1121173cb0c38942960f1b4a2e3792fc7df2.php(156): Twig\Template->display(Array)
#23 /the-site/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c2cbbbea5badabe638726e215ca8be730b2111c8d900bfda79b4e18209ba97ac->block_content(Array, Array)
#24 /the-site/storage/runtime/compiled_templates/f8/f84dab02c3d3bf6f89480c7fe46a7111fed2bd2bc09676a902d01a14ad2350e5.php(727): Twig\Template->displayBlock('content', Array, Array)
#25 /the-site/vendor/twig/twig/src/Template.php(184): __TwigTemplate_3e6385da23e8981cde3946e8ce2cec54eedfb55d83205279b402678835d63211->block_main(Array, Array)
#26 /the-site/vendor/twig/twig/src/Template.php(147): Twig\Template->displayBlock('main', Array, Array, false)
#27 /the-site/storage/runtime/compiled_templates/71/71bc443b4f6a5f594925965b89aeb29163ca858bee554cd6557d0772781e5163.php(465): Twig\Template->displayParentBlock('main', Array, Array)
#28 /the-site/vendor/twig/twig/src/Template.php(184): __TwigTemplate_7dc74f1e53f3641a764017f4b08ae5df0cb4bdcf6927131b4e38945ead080c7c->block_main(Array, Array)
#29 /the-site/storage/runtime/compiled_templates/f8/f84dab02c3d3bf6f89480c7fe46a7111fed2bd2bc09676a902d01a14ad2350e5.php(576): Twig\Template->displayBlock('main', Array, Array)
#30 /the-site/vendor/twig/twig/src/Template.php(184): __TwigTemplate_3e6385da23e8981cde3946e8ce2cec54eedfb55d83205279b402678835d63211->block_body(Array, Array)
#31 /the-site/storage/runtime/compiled_templates/15/15fd0bdbfd28b5cc71a4ecfd8f7d5017b79255243804d31a6cee407834514daf.php(75): Twig\Template->displayBlock('body', Array, Array)
#32 /the-site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_a352d30208a73120c6a1a85cefc7aa9c112b9591f023b4cae5e29a52993e0091->doDisplay(Array, Array)
#33 /the-site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#34 /the-site/storage/runtime/compiled_templates/b8/b8178a69f34dd73a3192cad83002f0ed077c61b1ef73f25b409b7edcdb499be0.php(56): Twig\Template->display(Array, Array)
#35 /the-site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_7bab94125e3f714aa4cca1b3c1c4a82e69780b0eed3b2f43fe2b53e053f38fe4->doDisplay(Array, Array)
#36 /the-site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#37 /the-site/storage/runtime/compiled_templates/f8/f84dab02c3d3bf6f89480c7fe46a7111fed2bd2bc09676a902d01a14ad2350e5.php(118): Twig\Template->display(Array, Array)
#38 /the-site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_3e6385da23e8981cde3946e8ce2cec54eedfb55d83205279b402678835d63211->doDisplay(Array, Array)
#39 /the-site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#40 /the-site/storage/runtime/compiled_templates/71/71bc443b4f6a5f594925965b89aeb29163ca858bee554cd6557d0772781e5163.php(148): Twig\Template->display(Array, Array)
#41 /the-site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_7dc74f1e53f3641a764017f4b08ae5df0cb4bdcf6927131b4e38945ead080c7c->doDisplay(Array, Array)
#42 /the-site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#43 /the-site/storage/runtime/compiled_templates/f5/f5786a68aadd3942d43017cad7ce1121173cb0c38942960f1b4a2e3792fc7df2.php(120): Twig\Template->display(Array, Array)
#44 /the-site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_c2cbbbea5badabe638726e215ca8be730b2111c8d900bfda79b4e18209ba97ac->doDisplay(Array, Array)
#45 /the-site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#46 /the-site/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#47 /the-site/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#48 /the-site/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#49 /the-site/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('entries/_edit', Array)
#50 /the-site/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('entries/_edit', Array)
#51 /the-site/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('entries/_edit', Array)
#52 /the-site/vendor/craftcms/cms/src/controllers/EntriesController.php(261): craft\web\Controller->renderTemplate('entries/_edit', Array)
#53 [internal function]: craft\controllers\EntriesController->actionEditEntry(Object(craft\models\Section), 3, NULL, NULL, Object(craft\models\Site), Object(craft\elements\Entry))
#54 /the-site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#55 /the-site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#56 /the-site/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('edit-entry', Array)
#57 /the-site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#58 /the-site/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('entries/edit-en...', Array)
#59 /the-site/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#60 /the-site/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#61 /the-site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#62 /the-site/web/index.php(21): yii\base\Application->run()
#63 {main}
```

**Comment by xaddict** [comment]
Why this is closed? It isn’t fixed, right?
