### ISSUE TITLE
Unknown Property Exception when creating a new tag having an SEO field type

### ISSUE THREAD

**Issue by ignercuit** [ethercreative/seo#260]
### Description
The web error log throws this error

```Getting unknown property: craft\elements\Tag::typeId```

### Steps to reproduce

1. Assign an SEO field to tag group field layout.

### Additional info

- Craft version: Craft Pro 3.3.11
- SEO version: 3.6.2
- PHP version: 7.2.16
- Database driver & version: MySQL 5.5.60
- Other Plugins: Tags Manager 1.0.5

**Comment by Tam** [comment]
@ignercuit Can you share the full stacktrace?

**Comment by ignercuit** [comment]
`yii\base\UnknownPropertyException: Getting unknown property: craft\elements\Tag::typeId in /Users/admin/Sites/craft3/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:`
#0 /Users/admin/Sites/craft3/vendor/craftcms/cms/src/base/Element.php(1102): yii\base\Component->__get('typeId')
#1 /Users/admin/Sites/craft3/vendor/ether/seo/src/fields/SeoField.php(240): craft\base\Element->__get('typeId')
#2 /Users/admin/Sites/craft3/vendor/twig/twig/src/Extension/CoreExtension.php(1499): ether\seo\fields\SeoField->getInputHtml(Object(ether\seo\models\data\SeoData), Object(craft\elements\Tag))
#3 /Users/admin/Sites/craft3/vendor/craftcms/cms/src/helpers/Template.php(96): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(ether\seo\fields\SeoField), 'getInputHtml', Array, 'method', false, false)
#4 /Users/admin/Sites/craft3/storage/runtime/compiled_templates/c1/c1ff34441fd82a566dab17013db999e94e6faf9ad3c05775cfb75278f8d07f8a.php(87): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(ether\seo\fields\SeoField), 'getInputHtml', Array, 'method')
#5 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(407): __TwigTemplate_53284badfaa931c8aa2b49433252ec7e415719723734e7af3780c7f4c6e3b6da->doDisplay(Array, Array)
#6 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /Users/admin/Sites/craft3/storage/runtime/compiled_templates/d0/d02f24266e27112152bc4eb5ec490b7b10dff66454247797d66d31c76e57a80a.php(58): Twig\Template->display(Array)
#8 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(407): __TwigTemplate_798a04491ab97d8af8bd19221bd6e7cced574ffbf79ad048c824175c8c25833b->doDisplay(Array, Array)
#9 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#10 /Users/admin/Sites/craft3/storage/runtime/compiled_templates/3a/3a0fd60ea479ad96fb46c02ef41e12ff3d3ebbb871b1fd41b2d94d615c334902.php(263): Twig\Template->display(Array)
#11 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(184): __TwigTemplate_ced5c97ddcb86f70f9d1f3ac835c603b9848021f289c843801b6db60df5b9d4e->block_content(Array, Array)
#12 /Users/admin/Sites/craft3/storage/runtime/compiled_templates/01/014f92f09bc717c73d6dc59b3c0b6a9caa88c97e2e8dd37c2a1792ef8260a01e.php(411): Twig\Template->displayBlock('content', Array, Array)
#13 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(184): __TwigTemplate_36f01e9d008688b22c1513d5f758bc8a5b7fc2aae3a25bbc7ccd1d50cf07c4dd->block_main(Array, Array)
#14 /Users/admin/Sites/craft3/storage/runtime/compiled_templates/01/014f92f09bc717c73d6dc59b3c0b6a9caa88c97e2e8dd37c2a1792ef8260a01e.php(266): Twig\Template->displayBlock('main', Array, Array)
#15 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(184): __TwigTemplate_36f01e9d008688b22c1513d5f758bc8a5b7fc2aae3a25bbc7ccd1d50cf07c4dd->block_body(Array, Array)
#16 /Users/admin/Sites/craft3/storage/runtime/compiled_templates/ae/aeca7dbfdc0af6da40cb8b3b18bec244056238d3d680c4344c74a0ce21a2e772.php(75): Twig\Template->displayBlock('body', Array, Array)
#17 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(407): __TwigTemplate_f585581b29f757647a64aedc032837463745baccbbfaa5db67b064e3f0bfd754->doDisplay(Array, Array)
#18 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /Users/admin/Sites/craft3/storage/runtime/compiled_templates/e0/e068a6c7c80b211fc75a22acc027be9ed77b3ba152d31ef40195382b2c77e34b.php(56): Twig\Template->display(Array, Array)
#20 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(407): __TwigTemplate_327707a8a202df22efbf1fbd43a9bd112f929a8a4e2be134a99b32c3dfc8d609->doDisplay(Array, Array)
#21 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /Users/admin/Sites/craft3/storage/runtime/compiled_templates/01/014f92f09bc717c73d6dc59b3c0b6a9caa88c97e2e8dd37c2a1792ef8260a01e.php(138): Twig\Template->display(Array, Array)
#23 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(407): __TwigTemplate_36f01e9d008688b22c1513d5f758bc8a5b7fc2aae3a25bbc7ccd1d50cf07c4dd->doDisplay(Array, Array)
#24 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /Users/admin/Sites/craft3/storage/runtime/compiled_templates/3a/3a0fd60ea479ad96fb46c02ef41e12ff3d3ebbb871b1fd41b2d94d615c334902.php(50): Twig\Template->display(Array, Array)
#26 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(407): __TwigTemplate_ced5c97ddcb86f70f9d1f3ac835c603b9848021f289c843801b6db60df5b9d4e->doDisplay(Array, Array)
#27 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#28 /Users/admin/Sites/craft3/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#29 /Users/admin/Sites/craft3/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#30 /Users/admin/Sites/craft3/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#31 /Users/admin/Sites/craft3/vendor/craftcms/cms/src/web/View.php(397): Twig\Environment->render('tag-manager/_ed...', Array)
#32 /Users/admin/Sites/craft3/vendor/craftcms/cms/src/web/View.php(458): craft\web\View->renderTemplate('tag-manager/_ed...', Array)
#33 /Users/admin/Sites/craft3/vendor/craftcms/cms/src/web/Controller.php(235): craft\web\View->renderPageTemplate('tag-manager/_ed...', Array, 'cp')
#34 /Users/admin/Sites/craft3/vendor/ether/tags/src/controllers/CpController.php(158): craft\web\Controller->renderTemplate('tag-manager/_ed...', Array)
#35 [internal function]: ether\tagManager\controllers\CpController->actionEdit('blog', NULL, NULL)
#36 /Users/admin/Sites/craft3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#37 /Users/admin/Sites/craft3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#38 /Users/admin/Sites/craft3/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('edit', Array)
#39 /Users/admin/Sites/craft3/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit', Array)
#40 /Users/admin/Sites/craft3/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('tag-manager/cp/...', Array)
#41 /Users/admin/Sites/craft3/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('tag-manager/cp/...', Array)
#42 /Users/admin/Sites/craft3/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#43 /Users/admin/Sites/craft3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#44 /Users/admin/Sites/craft3/web/index.php(21): yii\base\Application->run()
#45 {main}

**Comment by ignercuit** [comment]
@Tam I'm still experiencing the same error again even with the latest versions of Craft and SEO and Tags plugins.

Additional info
Craft version: Craft Pro 3.4.9
SEO version: 3.6.3
PHP version: 7.2.22
Database driver & version: MySQL 5.5.60
Other Plugins: Tags Manager 1.0.6

**Comment by ignercuit** [comment]
The issue here is when adding a SEO field on a tag group, it tries to check for the type ID. Tag doesn't have any typeID, only a group ID.

**Comment by baldhadhaval08** [comment]
@Tam @ignercuit 
I'm getting this error in craft 4 version. Is there any configuration I'm missing?
