### ISSUE TITLE
Sitemap group URL internal server error

### ISSUE THREAD

**Issue by icreatestuff** [ethercreative/seo#301]
### Description
The generated sitemap.xml file includes all the sub-urls for each of the enabled sections but one of them is returning an internal server error. Here's the output from the log file.

```
[-][1][rafrgeopu5s2tmf1g7c97bens9][error][yii\base\ErrorException:2] yii\base\ErrorException: First parameter must either be an object or the name of an existing class in /var/www/vhosts/cliffcollege.ac.uk/httpdocs/vendor/ether/seo/src/services/SitemapService.php:307
Stack trace:
#0 /var/www/vhosts/cliffcollege.ac.uk/httpdocs/vendor/craftcms/cms/src/web/ErrorHandler.php(74): yii\base\ErrorHandler->handleError(2, 'First parameter...', '/var/www/vhosts...', 307)
#1 [internal function]: craft\web\ErrorHandler->handleError(2, 'First parameter...', '/var/www/vhosts...', 307, Array)
#2 /var/www/vhosts/cliffcollege.ac.uk/httpdocs/vendor/ether/seo/src/services/SitemapService.php(307): property_exists(NULL, 'advanced')
#3 /var/www/vhosts/cliffcollege.ac.uk/httpdocs/vendor/ether/seo/src/controllers/sitemap/XmlController.php(25): ether\seo\services\SitemapService->core(Array)
#4 [internal function]: ether\seo\controllers\sitemap\XmlController->actionCore()
#5 /var/www/vhosts/cliffcollege.ac.uk/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /var/www/vhosts/cliffcollege.ac.uk/httpdocs/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#7 /var/www/vhosts/cliffcollege.ac.uk/httpdocs/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('core', Array)
#8 /var/www/vhosts/cliffcollege.ac.uk/httpdocs/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('core', Array)
#9 /var/www/vhosts/cliffcollege.ac.uk/httpdocs/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('seo/sitemap/xml...', Array)
#10 /var/www/vhosts/cliffcollege.ac.uk/httpdocs/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('seo/sitemap/xml...', Array)
#11 /var/www/vhosts/cliffcollege.ac.uk/httpdocs/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#12 /var/www/vhosts/cliffcollege.ac.uk/httpdocs/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /var/www/vhosts/cliffcollege.ac.uk/httpdocs/web/index.php(21): yii\base\Application->run()
#14 {main}
2020-04-28 21:12:28 [-][1][rafrgeopu5s2tmf1g7c97bens9][info][application] $_GET = [
    'p' => 'sitemap_sections_4_0.xml'
]
```
As far as I can tell all the other sitemap URLs are working as expected.

One other issue which I'm not sure is related or not is that under 'Custom URLs' I can't delete any rows, and a new row is generated each time I click Save.

### Additional info

- Craft version: 3.4.15
- SEO version: 3.6.4
- PHP version: 7.1.33
- Database driver & version: MySQL 5.7.30
- Other Plugins: Advanced URL Field, Button Box, Cookies, CP Field Inspect, Element API, Entries Subset, Feed Me, Freeform, Image Resizer, Imager, Inline SVG, Mailchimp Subscribe, Neo, Redactor, SuperSort, Super Table

**Comment by CMeldgaard** [comment]
+1

Experience the same on Craft 3.5.3. As far as i can see the error occurs when a entry type doesn't have the SEO Field.
