### ISSUE TITLE
SQL Error updating to 3.6.4

### ISSUE THREAD

**Issue by timmyomahony** [ethercreative/seo#305]
### Description

When I updated from `ether/seo` 3.6.4 to 3.6.5.1 on Craft Pro 3.4.19.1 and run

```
./craft migrate/all
```

I get the error:

```
Yii Migration Tool (based on Yii v2.0.35)

    > add column order integer NULL DEFAULT NULL to table {{%seo_redirects}} ... done (time: 0.001s)
Exception 'craft\errors\MigrateException' with message 'An error occurred while migrating SEO.'

in /home/forge/mysite.com/vendor/craftcms/cms/src/services/Updates.php:241

Stack trace:
#0 /home/forge/mysite.com/vendor/craftcms/cms/src/console/controllers/MigrateController.php(259): craft\services\Updates->runMigrations()
#1 [internal function]: craft\console\controllers\MigrateController->actionAll()
#2 /home/forge/mysite.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#3 /home/forge/mysite.com/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#4 /home/forge/mysite.com/vendor/yiisoft/yii2/console/Controller.php(164): yii\base\Controller->runAction()
#5 /home/forge/mysite.com/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction()
#6 /home/forge/mysite.com/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#7 /home/forge/mysite.com/vendor/craftcms/cms/src/console/Application.php(87): yii\console\Application->runAction()
#8 /home/forge/mysite.com/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#9 /home/forge/mysite.com/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest()
#10 /home/forge/mysite.com/craft(22): yii\base\Application->run()
#11 {main}
```

### Additional info

- Craft version: Pro 3.4.19.1
- SEO version: 3.6.4 to 3.6.5.1
- PHP version: 7.4.5
- Database driver & version: Pgsql
- Other Plugins:

**Comment by ItagMichael** [comment]
Hey @timmyomahony, did you resolve this? Having the same issue.

**Comment by timmyomahony** [comment]
Unfortunately I think I just uninstalled the plugin as a result.
