### ISSUE TITLE
Key "locked" for array with keys "-" does not exist.

### ISSUE THREAD

**Issue by driesbonte** [ethercreative/seo#349]
### Description

Twig\Error\RuntimeError: Key "locked" for array with keys "-" does not exist. in /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/ether/seo/src/templates/_seo/settings.twig:61
Stack trace:
#0 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'locked', Array, 'any', false, false)
#1 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/storage/runtime/compiled_templates/32/321342b3fdf473c635aab9aaaf2c53b55b4f6229835a72fc8dc2046b1460177f.php(128): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Array, 'locked', Array)
#2 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(405): __TwigTemplate_12ef58cd9fccdcfb5d88207f14f0d1318c334a563e3dbda9720dea7c63d6eeb2->doDisplay(Array, Array)
#3 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/storage/runtime/compiled_templates/30/30539bf1fd5e306febda757f4fdd8e5b2cff0e890a66625c63eb9112ebcfd01b.php(43): Twig\Template->display(Array)
#5 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(405): __TwigTemplate_885ff0c773ef7ff5bf3418249e315f6f8cd1b9c06a190feb857e566ba6e15eba->doDisplay(Array, Array)
#6 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#7 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/storage/runtime/compiled_templates/ba/ba386a586b2b565e1016ae7ade599f8dd4c84ba6c18ca603979f4439cb27109e.php(77): Twig\Template->display(Array)
#8 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(182): __TwigTemplate_2c1e2fd36a7c41d49730a198b40d03c276c6cffd66be8c08b167955c053a7b29->block_content(Array, Array)
#9 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/storage/runtime/compiled_templates/7d/7d8382cbc1c373a5d69d6280c2379b14c8635d62bbec31f5406b600b6e3c547e.php(497): Twig\Template->displayBlock('content', Array, Array)
#10 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(182): __TwigTemplate_b38a0a6e1cec6de79a065764744e98b4178d47c2854cb526b05fae90266e12c4->block_main(Array, Array)
#11 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/storage/runtime/compiled_templates/7d/7d8382cbc1c373a5d69d6280c2379b14c8635d62bbec31f5406b600b6e3c547e.php(316): Twig\Template->displayBlock('main', Array, Array)
#12 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(182): __TwigTemplate_b38a0a6e1cec6de79a065764744e98b4178d47c2854cb526b05fae90266e12c4->block_body(Array, Array)
#13 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/storage/runtime/compiled_templates/1b/1bac59e524e01e7a0cfa1415e3660a901254e1c1808758934ede035faed98794.php(90): Twig\Template->displayBlock('body', Array, Array)
#14 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(405): __TwigTemplate_761e8aff1473eef75730feb193b7709859651401d65559391f192a5fe29db25f->doDisplay(Array, Array)
#15 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/storage/runtime/compiled_templates/36/36fe9e814f8c75933e2798cb6d15ef8d0f7ca36e9b34d257701479c66c034b64.php(56): Twig\Template->display(Array, Array)
#17 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(405): __TwigTemplate_ae7b61b087994260497a7521b87160631acbb9eca05bbb77132d49ec5c494b63->doDisplay(Array, Array)
#18 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#19 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/storage/runtime/compiled_templates/7d/7d8382cbc1c373a5d69d6280c2379b14c8635d62bbec31f5406b600b6e3c547e.php(158): Twig\Template->display(Array, Array)
#20 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(405): __TwigTemplate_b38a0a6e1cec6de79a065764744e98b4178d47c2854cb526b05fae90266e12c4->doDisplay(Array, Array)
#21 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/storage/runtime/compiled_templates/ba/ba386a586b2b565e1016ae7ade599f8dd4c84ba6c18ca603979f4439cb27109e.php(48): Twig\Template->display(Array, Array)
#23 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(405): __TwigTemplate_2c1e2fd36a7c41d49730a198b40d03c276c6cffd66be8c08b167955c053a7b29->doDisplay(Array, Array)
#24 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#26 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#27 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#28 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/craftcms/cms/src/web/View.php(390): Twig\Environment->render('seo/settings', Array)
#29 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/craftcms/cms/src/web/View.php(451): craft\web\View->renderTemplate('seo/settings', Array)
#30 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/craftcms/cms/src/web/Controller.php(257): craft\web\View->renderPageTemplate('seo/settings', Array, 'cp')
#31 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/ether/seo/src/controllers/SettingsController.php(70): craft\web\Controller->renderTemplate('seo/settings', Array)
#32 [internal function]: ether\seo\controllers\SettingsController->actionIndex()
#33 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#34 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#35 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('index', Array)
#36 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('index', Array)
#37 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('seo/settings/in...', Array)
#38 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction('seo/settings/in...', Array)
#39 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/craftcms/cms/src/web/Application.php(259): yii\web\Application->handleRequest(Object(craft\web\Request))
#40 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#41 /Users/xxx/Sites/xxx/xxx-websites-2021/xxx/web/index.php(22): yii\base\Application->run()
#42 /Users/xxx/.composer/vendor/laravel/valet/server.php(191): require('/Users/driesbon...')
#43 {main}

### Additional info

- Craft version: Craft CMS 3.6.10
- SEO version: "ether/seo": "^3.6",
- PHP version: PHP 7.4.11

**Comment by driesbonte** [comment]
By rebuilding the config file everything was fixed.
